host: localhost:3000
info:
  contact: {}
  title: File uploader API
paths:
  /file/delete/{id}:
    get:
      consumes:
      - application/json
      description: Delete a file
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      tags:
      - file
  /file/mutiple_upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload mutiple files
      parameters:
      - description: File to upload
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      tags:
      - file
  /file/retrieve/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a file
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      tags:
      - file
  /file/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a single file
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      tags:
      - file
swagger: "2.0"
